### ISSUE TITLE
Is the Apple M1 chip a problem for sc3nb?

### ISSUE THREAD

**Issue by engek** [interactive-sonification/sc3nb#17]
Hi everyone, this is not really an issue, more a question: I might buy a new Mac Book with Apple's M1 Chip. Does anyone know if the M1 will become a problem for sc3nb? (I am rather new to both Python and Super Collider, I intend to use sc3nb for combining Sonification and Visualization) best, Kajetan

**Comment by engek** [comment]
Great! Thx a lot, that helps :) I will be using sc3nb a lot in the next weeks/months --> I am sure I can give feedback in some way or the other. best, Kajetan

**Comment by engek** [comment]
Hi again, just to let you know: I just used sc3nb with the M1 chip and it worked (I only tested the basic functionality - the server started and I can hear sound).  I used this beta version of super collider: https://cycling74.com/public-beta-download
best, Kajetan

**Comment by engek** [comment]
Hi again, just to let you know: I just used sc3nb with the M1 chip and it worked (I only tested the basic functionality - the server started and I can hear sound). I used SC 3.12.1 (macOS 10.13 and later).
best, Kajetan

**Comment by dreinsch** [comment]
Thank you for the update. 
Feel free to check out the example notebooks.
I am exciting to see what you are going to do. It might be possible to link to your project and/or include one or multiple notebooks that demonstrates some aspects on "How to combine Sonification and Visualization" in our [docs](https://interactive-sonification.github.io/sc3nb) in the User Guide or in a new section named something like Applications / Integrations.

**Comment by engek** [comment]
Absolutely! Let me come back to you when we have something to show :)
